[project]
name = "allen-vla"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=0.35.3",
    "lerobot[feetech]>=0.4.2",
    "opencv-python>=4.12.0.88",
    "pynput>=1.8.1",
    "uuid>=1.30",
]
